MODEX - data publication - I-O Table
OpenEnergyPlatform/data-preprocessing pull request #97
Opened 2022-04-04 14:30 UTC by chrwm

Closes #96

2022-05-05 16:34 UTC, jh-RLI requested changes

2022-05-06 10:41 UTC, steull approved these changes
I have adopted recommended changes from Jonas for the 'path' and 'timeseries' fields. The data looks good now.

2022-05-06 11:22 UTC, jh-RLI approved these changes

2022-05-09 07:09 UTC, merged

2022-05-09 07:09 UTC, steull commented
Metadata looks fine, table has been moved to 'reference' schema. 👍

2022-05-09 08:35 UTC, chrwm commented
Perfect, thank you!